### ISSUE TITLE
Training Tasks and Data for these LoRA modules?

### ISSUE THREAD

**Issue by StarLooo** [sail-sg/lorahub#12]
Hello, LoRAHub is a very interesting work!
I have the following two questions about the LoRA modules mentioned in the paper:
(1) According to the original paper, the FLAN-2022 Collection used for Flan-T5 instruction tuning consists of as many as 1836 tasks. However, in LoRAHub, it seems that only 196 tasks were used to train the LoRA modules. Can you please clarify if there is any misunderstanding here or if you selected these 196 tasks from the pool of 1836 tasks?
(2) LoRAHub trained each LoRA module using the same tasks as Flan-T5 for fairness. However, it seems that Flan-T5 sampled train examples from different tasks during training and did not use all the samples. Does this mean that even though LoRAHub's LoRA modules use the same tasks as Flan-T5, they may still use samples that Flan-T5 has not seen?

**Comment by SivilTaram** [comment]
@StarLooo Thanks for your interest on our work and thanks for your great questions!

(1) We use the publicly available dataset from https://huggingface.co/datasets/conceptofmind/FLAN_2022, which does not include all tasks. We choose to use the publicly available dataset because if is complex to reproduce the FLAN collection from the FLAN scripts 😓

As for the reason why the dataset cannot be fully released, you can checkout the author's [discussion](https://huggingface.co/datasets/conceptofmind/FLAN_2022) on the huggingface repo:
> Unfortunately, we had to exclude some data due to licensing constraints. So this is the closest replication that Shayne, the original author of FLAN, and I could publicly release.
> I will have to check with Shayne about the task naming conventions as well.
> There will be another much larger dataset released soon.
> Hopefully, this helps.


(2) In fact we randomly sample 10,000 examples from each task if there are more examples. I do not think the potential "extra" examples will have a big impact but, honestly, your mentioned problem may exist. Because the FLAN collection did not released the final dataset, we may not guarantee the above mentioned issues. Based on my experience, it does not have a great impact. Let me know if you want to discuss more!

**Comment by StarLooo** [comment]
@SivilTaram 
Thank you for your reply to my questions. I personaly agree that the usage of different samples of the same tasks won't have a big impact on the performance. And I forgot to ask an other question that:
I noticed that the experimental results on LoRAHub showcase the zero-shot and 5-shot performance of Flan-T5 Large on the BBH benchmark. However, the original paper "Scaling Instruction-Finetuned Language Models" tested Flan-T5 Large on BBH using 3-shot (to align with prior work), so there are some differences in the results on each held-out task compared to what LoRAHub displays (although coincidentally, both have an Avg Score of 37.5). Could you please explain the specific rationale behind choosing 5-shot instead of 3-shot in this context? Additionally, were the few-shot examples selected for BBH is manually constructed or released and fixed by the BBH benchmark itself?

**Comment by SivilTaram** [comment]
@StarLooo Thanks for your interesting question! We consider a 5-shot scenario instead of the traditional 3-shot scenario mainly because we think the potential of lorahub can be showcased given >=5 examples (just intuitive instead of empirical evidence). Given less than 5 examples, we do not think it would work (⚠️ no verification) for lorahub to optimise the weights of lora modules.

**Comment by StarLooo** [comment]
@SivilTaram Thank you, and how about the selection of few shot examples, is them from the BBH Benchmark itself or manually constructed by you?

**Comment by SivilTaram** [comment]
@StarLooo They are randomly selected from the BBH benchmark (We split the original BBH into two sets to study the effect of the number of examples). You can check the details in our released dataset https://github.com/sail-sg/lorahub/releases/download/0.1/data_bbh.zip

**Comment by StarLooo** [comment]
@SivilTaram Great. thanks!

**Comment by JornyWan** [comment]
sorry but there is no flan-2022 and no flan-task as you said
https://huggingface.co/datasets/conceptofmind/FLAN_2022
it showed not found.

**Comment by SivilTaram** [comment]
For those who are interested in the dataset, please refer to https://github.com/sail-sg/lorahub/issues/18 for more instructions.
