### ISSUE TITLE
Is there any scalability issue?

### ISSUE THREAD

**Issue by boyuZh** [sail-sg/lorahub#4]
Very interesting work! I have two questions and hope to get answer:
1. Does the performance improve as the number of LoRA models increases?
2. Have you conducted theoretical tests or experiments to validate the concept of LoraHub?

**Comment by SivilTaram** [comment]
@boyuZh thanks for your interest on our work!

1. This is indeed a great question! Generally, the performance follows a trend of initially increasing and then stabilizing or even being worse. This is because the limited few-shot examples may not provide sufficient information to adapt the weights if there are too many LoRA modules (e.g., > 100), leading to potential unstable problems.
2. We hope to do so but honestly we do not gain much insights from the internal analysis. We're still actively exploring it, and you may checkout some related works (presented in the Related work section) for inspiration.

**Comment by SivilTaram** [comment]
Closed since no more activity.
